#
# Your Crowdin credentials
#
"project_id": "676278"
"api_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6ImYwMmE5MjEwMmQxODI2MmYxMTRiY2U3ODQ3ZDFhMTk1YTZhNTczZDg5Yzc4YWMwZTVlYWY5NmE5NDk4M2Y1ODUxZmFkZmQ0YmNmZGVmYzc4IiwiaWF0IjoxNzE1ODU4Njc1Ljk3NTkxMywibmJmIjoxNzE1ODU4Njc1Ljk3NTkxNSwiZXhwIjoxNzQ3Mzk0Njc1Ljg5MDgwMiwic3ViIjoiMTYzNzM5MTIiLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.cr3n3c4AGjMaEb58fxfjLFOtRg5cgmgdXHyR1dUje-PaZadb_1Gr8-ng8wTJkcZZDquI8RZyx8RWj4Wz2wSiZAoiGHjMkEpe-2Smh2h--3mTDn7ai3n3phjsNgIBkfzhVBSuN0aZblBC99btlfMy0oXn6OIDqj_BqjIRxyeDGKNkvW2R-Lp0-Pug3NyVfwrcmvZmIeEEVsmHu5RucQZ6jbuY6YTwuZOI9zLPee1FUmHbTJ0DM97V3CfUgQoig5UAtdgfv2f3jOuDpSDwQvhMzzhwg64wW7e4CvMRS7SewbapOe3UArVFFz97lOJsviRu5agJMwq1ALlSA0eeaZSbhmiAyox2bulqbJ0vHnhAqkAVJr7lHrEKW35IyF2XOVFqQUquSoCaszHaGYIBf_h9gTAui7-P_8DXT2ElweJo-0Z9GbN93oQel8cbdgQinS3DhR0_zJhnN4jSbocilaCuldZScDtgDh_nHS_2sWRjeVx2E3E_sKn7PGZLa006FO0gAdDpztek9Ybg_w3i1hJCbBDwFDhmeW7rHXY6UzAvR4jiA3YTw4B9SFs0M_QGjXpC9AdA7tIzaUtPBTFMFcT3dWNZHisjgOMZCUplP4SAxRvLGnLeeE6KOW8AAU20MTB4qWuDCWufVYRFKGCP7B8boTZvHRxZ7073ZHxUAxHspBs"
"base_path": "."
"base_url": "https://api.crowdin.com"
files: [{
    "source": "src/locales/en/auto-generated/translation.json",
    "translation": "src/locales/%two_letters_code%/auto-generated/translation.json",
    "type": "i18next_json"
}, ]