name: Deploy

on:
  push:
    branches: [ test_instance ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
      - name: Removing previous build
        run: sudo rm -rf /var/www/pokerogue
        shell: bash
      - name: Moving build to apache
        run: sudo cp -r //home/greenlamp/download/important/actions-runner/_work/pokerogue/pokerogue/dist /var/www/pokerogue/
        shell: bash
      - name: Changing build owner
        run: sudo chown greenlamp:greenlamp /var/www/pokerogue
        shell: bash